apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudknowledge
spec:
  selector:
    matchLabels:
      app: cloudknowledge
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  template:
    metadata:
      labels:
        app: cloudknowledge
    spec:
      containers:
      - name: cloudknowledge
        image: sdubey/kubernitiesproject
        imagePullPolicy: Always
        ports:
        - containerPort: 80
