apiVersion: v1
kind: Service
metadata:
  name: cloudknowledge
  label:
    app: cloudknowledge
spec:
  selector:
    app: cloudknowledge
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 80
      NodePort: 31200
